/* eslint-disable functional/immutable-data */

module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:eslint-comments/recommended",
    "plugin:functional/external-recommended",
    "plugin:functional/recommended",
    "plugin:import/errors",
    "plugin:jest-formatting/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:react/recommended",
    "plugin:react/jsx-runtime",
    "prettier",
  ],
  plugins: [
    "@typescript-eslint",
    "functional",
    "jest-formatting",
    "jest",
    "prefer-arrow",
    "promise",
    "react-hooks",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: ["./tsconfig.json"],
  },
  env: {
    es6: true,
    node: true,
    browser: true,
    "jest/globals": true,
  },
  settings: {
    react: { version: "detect" },
    linkComponents: ["Link"],
    "import/resolver": { alias: true },
  },
  rules: {
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-inferrable-types": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        args: "after-used",
        argsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/prefer-ts-expect-error": "error",
    "arrow-body-style": ["error", "as-needed"],
    "default-case": "error",
    eqeqeq: ["error", "smart"],
    "eslint-comments/no-unused-disable": "error",
    "functional/functional-parameters": "off",
    "functional/no-class": "off",
    "functional/no-conditional-statement": "off",
    "functional/no-expression-statement": "off",
    "functional/no-method-signature": "error",
    "functional/no-mixed-type": "off",
    "functional/no-return-void": "off",
    "functional/no-this-expression": "off",
    "functional/no-throw-statement": "off",
    "functional/no-try-statement": "off",
    "functional/no-let": [
      "error",
      { allowLocalMutation: true, ignorePattern: "^mutable" },
    ],
    "functional/immutable-data": [
      "error",
      {
        ignorePattern: ["^mutable"],
        ignoreAccessorPattern: "^*",
        ignoreImmediateMutation: true,
        assumeTypes: true,
      },
    ],
    "functional/prefer-readonly-type": ["error", { ignorePattern: "^mutable" }],
    "import/imports-first": "error",
    "import/named": "off",
    "import/namespace": "off",
    "import/newline-after-import": "error",
    "import/no-unresolved": "off",
    "import/order": [
      "error",
      {
        pathGroups: [
          {
            pattern: "~/**",
            group: "external",
            position: "after",
          },
        ],
        "newlines-between": "always",
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
    "no-console": ["warn", { allow: ["info", "warn", "error", "dir"] }],
    "no-duplicate-imports": "error",
    "no-irregular-whitespace": "off",
    "no-prototype-builtins": "off",
    "no-undef": "off",
    "no-undefined": "off",
    "no-var": "error",
    "object-shorthand": "error",
    "prefer-arrow-callback": "error",
    "prefer-arrow/prefer-arrow-functions": "error",
    "prefer-const": "error",
    "promise/catch-or-return": "error",
    radix: "error",
    "react-hooks/exhaustive-deps": "error",
    "react-hooks/rules-of-hooks": "error",
    "react/display-name": "off",
    "react/forbid-component-props": ["error", { forbid: ["style"] }],
    "react/forbid-dom-props": ["error", { forbid: ["style"] }],
    "react/jsx-boolean-value": "error",
    "react/jsx-no-bind": "error",
    "react/jsx-no-useless-fragment": "error",
    "react/no-deprecated": "off",
    "react/no-direct-mutation-state": "off",
    "react/no-string-refs": "off",
    "react/prop-types": "off",
    "react/require-render-return": "off",
    "sort-imports": ["error", { ignoreDeclarationSort: true }],
  },
};

/* eslint-enable functional/immutable-data */
