name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: yarn install
        run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn lint
